module4-task2 tests
htmlacademy-nodejs/338401-typoteka-3 pull request #11
Opened 2021-09-24 14:23 UTC by Fedos2589

2021-09-24 15:11 UTC, what1s1ove requested changes
нужно убрать весь закоменченный код, и большие буквы с названий файлов

2021-09-24 15:11 UTC, what1s1ove commented on package.json
> +    "joi": "^17.4.2",
версии всех пакетов должны быть зафиксированы

2021-09-24 15:11 UTC, what1s1ove commented on src/service/api/articles.e2e.test.js
> +// const mockCategories = [
законменченный код нужно убрать (во всех файлах)

2021-09-24 15:11 UTC, what1s1ove commented on src/service/middlewares/articleExists.js
> +'use strict';
в названии файлов не должно быть больших букв (подправить везде)

2021-10-05 15:43 UTC, what1s1ove requested changes

2021-10-05 15:43 UTC, what1s1ove commented on src/service/api/articles.js
> +  app.use(`/articles`, router);
```suggestion

module.exports = (app, articleService, commentService) => {
const router = new Router();

  app.use(`/articles`, router);
```

Сделай такое на всех роутах. Нужно чтобы все роуты генерировали новые пути через функцию. Дальше без этого будет сложно, и будет лишние непонятки.

2021-10-06 09:23 UTC, Fedos2589 commented on src/service/api/articles.js
> +  app.use(`/articles`, router);
+

2021-10-06 12:47 UTC, what1s1ove approved these changes

2021-10-06 12:47 UTC, merged